#!/usr/bin/env bash

get_status_icon() {
    if pactl list | sed -n '/^Source/,/^$/p' | grep Mute | grep yes >/dev/null; then
        echo -n ""
    else
        echo -n "🎙️"
    fi
}

get_status_icon
