#!/bin/bash

icon=''
interface=''

profile=$(netctl list | grep '*' | cut -c 3-)

if [ -z "$profile" ]; then
    echo -ne "Down"
fi

case $profile in
    'ethernet_static')
        icon='E: '
        interface='eno1'
        ;;
    'wireless_static')
        icon='W: '
        interface='wlan0'
        ;;
    'bond_failover')
        icon='bo: '
        interface='bond0'
        ;;
    'bridge_ethernet')
        icon='br: '
        interface='br0'
        ;;
    *)
        exit 1
        ;;
esac

ip_addr=$(ip address show "$interface" | grep -o "[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*" | head -1)
ip_state=$(ip address show "$interface" | grep 'state UP')

if [ -z "$ip_state" ]; then
    echo -ne "Down"
else
    echo -ne "$icon$ip_addr"
fi
